version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./jvm/src/main/resources/ziam_schema.sql:/docker-entrypoint-initdb.d/ziam_schema.sql
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: ziam
    ports:
      - "5432:5432"