addSbtPlugin("io.spray"                % "sbt-revolver"             % "0.10.0")
addSbtPlugin("org.scala-js"            % "sbt-scalajs"              % "1.13.2")
addSbtPlugin("org.portable-scala"      % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("ch.epfl.scala"           % "sbt-scalafix"             % "0.11.0")
addSbtPlugin("com.eed3si9n"            % "sbt-assembly"             % "2.1.1")
addSbtPlugin("org.playframework.twirl" % "sbt-twirl"                % "2.0.7")
