name: Ziam Bot CI
on: 
  push: 
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'sbt'
      - name: Make default db folder
        run: mkdir -p databases
      - name: Build and Test
        run: sbt -v +test
