name: Ziam Bot CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Make default db folder
        run: mkdir -p databases
      - name: Build and Test
        run: sbt -v +test
